# Generated by Django 3.2.5 on 2023-08-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pets.Tag'),
        ),
    ]
